### PR TITLE
Move test_benchmarks.py and test_workflow.py fixtures to conftest.py file

### PR DESCRIPTION
**Pull request by dorothykiz1**
xref #1030

### CODE REVIEW

**Comment by datapythonista** [comment]
Looks like one of the fixtures you're creating in the new file, is not the one you're deleting from the other file.

**Comment by dorothykiz1** [comment]
> Looks like one of the fixtures you're creating in the new file, is not the one you're deleting from the other file.

Thanks, @datapythonista  for your review, seen my mistake and have removed and resolved it, the other fixture in test/test_publish.py already exists in conftest.py ,so i didn't add it

**Comment by dorothykiz1** [comment]
@datapythonista this PR is ready for your review

**Comment by datapythonista** [comment]
Thanks @dorothykiz1

**Pull request merged**
