### PR TITLE
BUG: Parse pip in env better

### LINKED ISSUE #1326: mamba plugin in asv 0.6.0: ValueError: too many values to unpack (expected 2)
```bash
   for pkgname, pipval in pip_args:
ValueError: too many values to unpack (expected 2)
```

```bash
(Pdb) pip_args
[('asv_runner', None), ('pympler', None), 'numpydoc=1.1.0']
```

### PR DESCRIPTION
**Pull request by HaoZeke**
Closes #1326.

### CODE REVIEW

**Comment by mattip** [comment]
Is there a way to test this?

**Comment by HaoZeke** [comment]
> Is there a way to test this?

Yup, reworked and added tests.

**Comment by HaoZeke** [comment]
Should be good to go now @mattip, since the pypy tests are still flakey on the CI (will reopen the older issue on it).

**Comment by mattip** [comment]
Appveyor [is unhappy](https://ci.appveyor.com/project/airspeed-velocity/asv/builds/47870677#L1148), there are two failed tests

**Comment by HaoZeke** [comment]
Also fixes the unintended regression [noted by sympy](https://github.com/sympy/sympy/pull/25562#issuecomment-1704387414) w.r.t `virtualenv` environments.

**Comment by HaoZeke** [comment]
PyPy failure is unrelated, should be good to go @mattip :)

**Comment by mattip** [comment]
There is a merge conflict.

**Comment by HaoZeke** [comment]
> There is a merge conflict.

Fixed now :)

**Comment by mattip** [comment]
I merged this, perhaps a future refactor could leverage conda/mamba rather than re-implementing the logic here.

**Pull request merged**
