### PR TITLE
MAINT: Convert almost everything to f-strings

### PR DESCRIPTION
**Pull request by HaoZeke**
With `flynt`. Superceedes https://github.com/airspeed-velocity/asv/pull/1198, https://github.com/airspeed-velocity/asv/pull/1197, https://github.com/airspeed-velocity/asv/pull/1196, https://github.com/airspeed-velocity/asv/pull/1245.

### CODE REVIEW

**Comment by mattip** [comment]
This has a merge conflict

**Comment by mattip** [comment]
Does this take into account the comments in #1245?

**Comment by HaoZeke** [comment]
> Does this take into account the comments in #1245?

Yup, most of them are not relevant since `extern` has been removed. However, for this:

> Nit: it is a bit weird to be using these old versions of python (line 39?) and numpy (dunno where that comes from). If not too much trouble could you update them? If not no big deal.

I'm not sure they should be updated here, since those are part of the `asv` files generated for the tests, might be good to have an issue.

**Comment by mattip** [comment]
Thanks @HaoZeke

**Pull request merged**
