### PR TITLE
ENH: Return pstats.Stats for --profile

### LINKED ISSUE #971: Question: How to use/extract profiling data after running 'asv run -p'
First of all thanks for the awesome tool ❤️ 

I'm wondering how to access the profiling data recorded when using `asv run` with the `-p` flag.
I can't find profiling anywhere in the generated HTML page (`asv publish`), nor can I find a config option or flag to add it to the HTML page (maybe I'm just blind 😅 ). 

So I'm wondering what to do after recording the profiling data.

I saw that the result json files have a key `profiles` containing benchmark names as keys and a massive text blob as value (`base64` of the `pstat` binary blob?).
So is the intended use to parse the result json file, decode the blob and then process it with a tool like `gprof2dot`?

Thanks in advance for clarifying

### PR DESCRIPTION
**Pull request by HaoZeke**
This, along with documentation changes chronicles how to use the results of `asv run --profile`. Closes #971, #808, #801, #71.

Addresses (7) of https://github.com/airspeed-velocity/asv/issues/1219#issuecomment-1270968475.

### CODE REVIEW

**Comment by HaoZeke** [comment]
@mattip I think this should be good to go as well.

**Comment by mattip** [comment]
Thanks @HaoZeke

**Comment by mattip** [comment]
Any thoughts about why this might have [timed out on PyPy3.7](https://github.com/airspeed-velocity/asv/actions/runs/4775650402/jobs/8490113288#step:7:496)? I think we should drop that version from CI since it is no longer supported. We could add PyPy3.9 instead...

**Comment by HaoZeke** [comment]
> Any thoughts about why this might have [timed out on PyPy3.7](https://github.com/airspeed-velocity/asv/actions/runs/4775650402/jobs/8490113288#step:7:496)? I think we should drop that version from CI since it is no longer supported. We could add PyPy3.9 instead...

I'm not sure, the PyPy tests are pretty flakey though, especially 3.7, I've opened https://github.com/airspeed-velocity/asv/pull/1276 to switch to 3.9.

**Pull request merged**
