### PR TITLE
MAINT: Vendor `mamba.api`

### LINKED ISSUE #1353: BUG: "environment_type": "mamba" fails
On both MacOs and Windows, I'm unable to use mamba (which is problematic since conda is timing out when run in asv on windows). On both I get the same error 

```
* Unknown environment type 'mamba'
* No environments selected
```

pip show indicates that I'm up-to-date with asv 0.6.1.

Maybe I'm missing something in my setup, but I've looked through the documentation as much as I can and dont see anything I find as germane. 

Thanks for your help.

### PR DESCRIPTION
**Pull request by HaoZeke**
Closes #1353. Also addresses comments in #1370. There's an upstream clarification issue in https://github.com/mamba-org/mamba/issues/3159. However, I think this makes sense to go in as-is. Will cut a release soon with the fix.

### CODE REVIEW

**Comment by HaoZeke** [comment]
Might also be of interest to @dstansby and / or @hmaarrfk 😃

**Comment by HaoZeke** [comment]
The `pypy-3.8` failure is unrelated (the timeouts for `pypy` are pretty random and unrelated to changes in PRs).

**Comment by hmaarrfk** [comment]
if this helps resolve the challenges with context not being initialized correctly that is great!

I will say that now that conda-libmamba-solver has been deployed, there is little advantage of using "mamba", and you may want to just "avoid churn".

Thanks for keeping this project working all these years!

**Comment by HaoZeke** [comment]
> if this helps resolve the challenges with context not being initialized correctly that is great!

That bug-fix is next, this is to get the `mamba` solver up and running again. I was wondering if you had a reproducible example I could play with where the `.condarc` needs to be read and isn't.
 
> I will say that now that conda-libmamba-solver has been deployed, there is little advantage of using "mamba", and you may want to just "avoid churn".

I understand `conda` uses `libmamba` as an alternate backend, but for a while (couple of releases) I will probably keep the plugin in (also in my tests `conda` is still a bit slower).
 
> Thanks for keeping this project working all these years!

Glad its still in use! (though I'm a relatively new maintainer, 7-8 months tops I guess).

**Comment by HaoZeke** [comment]
Draft for a bit, the plugin is still rather fragile (the most compatible way to use it seems to be to keep `mamba.api` **as is** and enforce that the user resolves dependencies via `micromamba install libmambapy conda conda-build mamba`.

Otherwise (without `mamba.api`):

```
❯ asv run --launch-method spawn
· Creating environmentsconda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache

·· Failure creating environment for mamba-py3.9-numpy1.21
Traceback (most recent call last):
  File "/home/rgoswami/micromamba/envs/asv_exp/bin/asv", line 8, in <module>
    sys.exit(main())
  File "/home/rgoswami/Git/Github/Quansight/asvWork/asv/asv/main.py", line 29, in main
    result = args.func(args)
  File "/home/rgoswami/Git/Github/Quansight/asvWork/asv/asv/commands/__init__.py", line 49, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/rgoswami/Git/Github/Quansight/asvWork/asv/asv/commands/run.py", line 166, in run_from_conf_args
    return cls.run(
  File "/home/rgoswami/Git/Github/Quansight/asvWork/asv/asv/commands/run.py", line 278, in run
    Setup.perform_setup(environments, parallel=parallel)
  File "/home/rgoswami/Git/Github/Quansight/asvWork/asv/asv/commands/setup.py", line 82, in perform_setup
    list(map(_create, environments))
  File "/home/rgoswami/Git/Github/Quansight/asvWork/asv/asv/commands/setup.py", line 14, in _create
    env.create()
  File "/home/rgoswami/Git/Github/Quansight/asvWork/asv/asv/environment.py", line 740, in create
    self._setup()
  File "/home/rgoswami/Git/Github/Quansight/asvWork/asv/asv/plugins/mamba.py", line 130, in _setup
    solver = MambaSolver(
  File "/home/rgoswami/Git/Github/Quansight/asvWork/asv/asv/plugins/_mamba_helpers.py", line 156, in __init__
    self.index = load_channels(
  File "/home/rgoswami/Git/Github/Quansight/asvWork/asv/asv/plugins/_mamba_helpers.py", line 141, in load_channels
    repo = subdir.create_repo(pool)
libmambapy.bindings.MambaNativeException: Cache not loaded
```

**Comment by HaoZeke** [comment]
Should be good to go now. Works with only `libmambapy` and `conda` installed.

**Comment by HaoZeke** [comment]
@mattip does this look alright? I'm thinking of this, #1375 and #1373 along with a minor documentation update (taking in the `asv-memray` plugin) for a release this weekend if everything goes well.

**Comment by mattip** [comment]
The [upstream issue](https://github.com/mamba-org/mamba/issues/3159) says, in justifying removing the API functions:
> no more logic will be done on the Python side.

and
>  do not hesitate to report here all the APIs you need and you cannot find in the libmambapy folder

It seems some of the functionality here should be reported upstream as missing, so that we can get rid of the helper class eventually.

**Comment by mattip** [comment]
Is there a test that was failing before this PR and now passes? I don't see any test changes.

**Comment by HaoZeke** [comment]
> The [upstream issue](https://github.com/mamba-org/mamba/issues/3159) says, in justifying removing the API functions:
> 
> > no more logic will be done on the Python side.
> 
> and
> 
> > do not hesitate to report here all the APIs you need and you cannot find in the libmambapy folder
> 
> It seems some of the functionality here should be reported upstream as missing, so that we can get rid of the helper class eventually.

My reading of that was just that the API functionality needed (also in `boa`) was meant to be handled at this level, the `MambaSolver` class is part of the documentation and is noted as an "example of using `libmambapy`" and subsequently needed tweaking (liberally lifted from `boa`) but yes it would be great to remove this eventually.

**Comment by HaoZeke** [comment]
> Is there a test that was failing before this PR and now passes? I don't see any test changes.

I hadn't written a CI test for `mamba` before, so I've added that now for this PR.

**Comment by mattip** [comment]
Thanks @HaoZeke. [mamba test is passing](https://github.com/airspeed-velocity/asv/actions/runs/7770516622/job/21190807177?pr=1372#step:6:19)

**Pull request merged**
