### PR TITLE
BUG: fix JSONC support

### PR DESCRIPTION
**Pull request by lucascolley**
@HaoZeke I think this should be it! close gh-1425

### CODE REVIEW

**Comment by lucascolley** [comment]
CI isn't happy although I'm struggling to decipher the error messages.

**Review by HaoZeke — APPROVED** [review]

**Comment by lucascolley** [comment]
I want to say the CI failure looks unrelated?

**Comment by HaoZeke** [comment]
It is odd, especially since it isn't surprising at all that the extension (a **C-Python** extension) will fail on PyPy.. I'd have thought it wouldn't even try to build it there..

**Comment by mattip** [comment]
TL;DR: Please pin setuptools to a known good version and only update it after checking that it works. 

This was reported as pypy/pypy#5004 and is due to a new setuptools release, which vendors pypa/distutils, which started requiring a default sysconfig value that PyPy did not supply pypa/distutils#280.

**Comment by lucascolley** [comment]
CI is happy after pinning setuptools in this PR. This should be good to go.

**Comment by HaoZeke** [comment]
Thanks @lucascolley and @mattip
Will cut another release tomorrow probably.

**Pull request merged**
