### PR TITLE
replaced format

### PR DESCRIPTION
**Pull request by aziizziana**

### CODE REVIEW

**Comment by datapythonista** [comment]
@dorothykiz1 do you mind reviewing this please?

**Comment by dorothykiz1** [comment]
@aziizziana Thanks for working on this, i have left a couple of comments ,make changes on all the files as i see the problem is the same for all

**Comment by datapythonista** [comment]
@aziizziana do you have time to fix this PR based on the comments?

**Comment by datapythonista** [comment]
Closing as stale. @aziizziana if you want to continue working on this, please ping me, and I can reopen this PR.

**Pull request closed without merging**
