### PR TITLE
CI: Try windows on github again

### PR DESCRIPTION
**Pull request by HaoZeke**
Continuing from #1119.

### CODE REVIEW

**Comment by HaoZeke** [comment]
3.7 on [windows GHA works](https://github.com/airspeed-velocity/asv/actions/runs/5967757252/workflow) with `virtualenv`. The AppVeyor configuration uses `conda`.

**Comment by HaoZeke** [comment]
@mattip I think this is good to go, feature compatible with the existing appveyor configuration and runs faster.

**Comment by mattip** [comment]
CI on windows is failing, both on appveyor and on github actions

**Comment by HaoZeke** [comment]
@mattip this should be ready to go, appveyor fails because the configuration has been removed.

**Comment by mattip** [comment]
Cool, thanks. I will remove the appveyor integration from the repo.

**Pull request merged**
