### PR TITLE
Add codespell config, pre-commit hook, and GH action (to catch new typos) + make it fix some it finds

### PR DESCRIPTION
**Pull request by yarikoptic**
TODO
- [x] remove TEMP commit after seeing if pre-commit workflow catches it
- [x] remove github action if pre-commit wf catches it

### CODE REVIEW

**Comment by yarikoptic** [comment]
ok, pre-commit works but needs duplication for excludes. I might just exclude that specific name... and we do not need dedicated GH action -- will remove it.

**Review by HaoZeke — CHANGES_REQUESTED** [review]
LGTM, could the commits be reworded with a MAINT: tag? (and also squashed, I think one MAINT: commit adding the config and one DOC: using it should suffix).


Sorry for the delayed review!

**Comment by yarikoptic** [comment]
done -- one commit rebased and squashed now

**Comment by yarikoptic** [comment]
Failing CI runs seems to not relate

**Pull request merged**
