### PR TITLE
MAINT: Finalize rename to `main`

### PR DESCRIPTION
**Pull request by HaoZeke**
Part of #1368.

### CODE REVIEW

**Comment by mattip** [comment]
Could you add a release note? I think this could have an impact on projects that still use `master' as the default branch: they will need to now use a non-default configuration, right?

**Comment by HaoZeke** [comment]
> Could you add a release note? I think this could have an impact on projects that still use `master' as the default branch: they will need to now use a non-default configuration, right?

I'm not sure it will though, if the projects have an existing `asv.config.json` they shouldn't be affected. Internally `asv` still assumes `master` even after this simply because `asv` shouldn't be responsible for making changes to `git` configurations and that still defaults to `master`. The default example config has changed, but that shouldn't be a breaking change.

I will add a release note.

**Comment by mattip** [comment]
Thanks @HaoZeke

**Comment by mattip** [comment]
The release note can be part of the general release

**Pull request merged**
