### PR TITLE
MAINT: Update Rpy2 tests

### LINKED ISSUE #1101: Add rpy2 to dependencies, to run R test in CI
Looks like this test is being skipped in the CI, because of the missing `rpy2` dependency:
```
test/test_statistics.py::test_mann_whitney_u_R SKIPPED (Requires rpy2)   [ 79%]
```

We should add it, and make sure the test is being executed after it.

### PR DESCRIPTION
**Pull request by HaoZeke**
Also runs them in the CI. Closes #1101.

### CODE REVIEW

**Comment by mattip** [comment]
There is a merge conflict in this PR now.

**Comment by HaoZeke** [comment]
> There is a merge conflict in this PR now.

Fixed :)

**Comment by mattip** [comment]
Ugh. I broke the merge here again.

**Comment by HaoZeke** [comment]
> Ugh. I broke the merge here again.

Sorry, my bad, should be good to go now.

**Comment by mattip** [comment]
Thanks @HaoZeke. Please ping me if there are more PRs ready for final review.

**Pull request merged**
