### PR TITLE
MAINT,DOC: `pip` and network connectivity defaults

### LINKED ISSUE #1356: Bad out-of-box support for PDM-based builds
I am adding ASV to [mismo](https://github.com/nickcrews/mismo/), which uses PDM as the project manager and build tool.

With no `build_command` specified in the asv.conf.json, then since the project has a pyproject.toml, the following default build command is used:

https://github.com/airspeed-velocity/asv/blob/b8cbf81ccb808158102692a6fc42b8a9b2f2861e/asv/environment.py#L918-L923

However, this fails, because the build dependency of `pdm.backend`, but the various flags there disallow going to PyPI to fetch it (as I understand it, perhaps the root cause is different). In order to get the build to work, I have to use
`python -mpip wheel -w {build_cache_dir} {build_dir}`

Why do we disallow fetching to PyPI? It seems like fetching the build backend is going to be needed in many cases, including pdm.backend, poetry-core, and hatchling? Is there something else we can do to make the out-of-box experience better for these users?

### PR DESCRIPTION
**Pull request by HaoZeke**
Closes #1356.

### CODE REVIEW

**Comment by mattip** [comment]
Is there a sample test project with a `pyproject.toml`?

**Comment by HaoZeke** [comment]
> Is there a sample test project with a `pyproject.toml`?

Yes, but it needs a newly released `asv_runner` first, will prepare the release ASAP.

**Comment by HaoZeke** [comment]
@mattip this should now be good to go.

**Comment by HaoZeke** [comment]
CI failure is real, needs `importlib.metadata` on 3.7, cutting a new bugfix release for asv_runner.

**Comment by HaoZeke** [comment]
@mattip finally ready ^_^

**Comment by mattip** [comment]
Thanks @HaoZeke

**Pull request merged**
