### PR TITLE
Move example-results fixture to conftest.py file 

### PR DESCRIPTION
**Pull request by dorothykiz1**
xref #1030

### CODE REVIEW

**Comment by dorothykiz1** [comment]
@datapythonista this PR is ready for your review

**Comment by datapythonista** [comment]
Thanks @dorothykiz1. It'd be better to not mix things, like moving the fixture and fixing flake8 issues, in the same PR. Better to address them separately.

**Comment by dorothykiz1** [comment]
Thanks @datapythonista totally agree,however i have noticed if i make changes the CI flags If the files are not Flake 8 compliant

**Comment by datapythonista** [comment]
I see. It would still be better to open a PR first for flake8 or any file you need, and then a separate PR for the move.

**Comment by dorothykiz1** [comment]
Thanks for your guidance, i will follow this.

**Pull request merged**
